

                  Peter's amd64+nomultilib LiveCD


new versions can be downloaded from https://subdimension.ro
mail <2b4eda@subdimension.ro> for bug reports

 'server'      - boots a server kernel (console)
 'server-vga'  - boots a server kernel (vga fb)
 'local'       - boots the first hard drive
 'next'        - tells the bios to boot the next device from it's list

the 'server' option will be loaded after a 2 minute delay
