#!/bin/bash

trap - INT QUIT TSTP
export PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /etc/init/functs.sh

rc_sysinit() {

	#ebegin 'populate /dev'
	#[ -e /mnt/cdrom/zisofs/dev.tar ] && tar -xpf /mnt/cdrom/zisofs/dev.tar -C /dev/
	#[ -e /mnt/livecd/dev.tar ] && tar -xpf /mnt/livecd/dev.tar -C /dev/
	#/sbin/udevd /dev

	ebegin 'mount filesystems'
	#mount -t proc -o nosuid,noexec proc /proc
	#mount -a
	mount -o remount,rw /

	ebegin 'udev, dbus'
	udevd --daemon
	udevadm trigger --type=subsystems --action=add
	udevadm trigger --type=devices

	mkdir -p /dev/shm
	mount /dev/shm

	mkdir -p /dev/pts
	mount /dev/pts

}

rc_start_network() {

	ebegin 'setup networking'
	hostname livecd
	ip addr add 127.0.0.1/8 brd 127.255.255.255 dev lo
	ip link set lo up

}


rc_network() {

	rc_start_network

	ebegin 'start services'
	sysctl -q -w net.ipv4.ip_forward=0
	sysctl -q -w kernel.panic=3
	sysctl -q -w kernel.panic_on_oops=1
	sysctl -q -w kernel.printk="3 4 1 3"
	mkdir -p /var/run
	cat /var/run/random-seed > /dev/urandom 2>/dev/null
	ssh-keygen -A &>/dev/null
	/usr/sbin/sshd
	grep -q 'acpi=off' /proc/cmdline || /usr/sbin/acpid
}

rc_nonetwork() {
	:
	#ebegin 'start system logger'
	#syslog-ng
}

rc_shutdown() {
	#ebegin 'send sigterm and sigkill'
	#/sbin/killall5 -15
	#sleep 2
	#/sbin/killall5 -9
	ebegin 'unmount filesystems'
	/bin/mount -a -o remount,ro &>/dev/null
	#/bin/umount -a &>/dev/null
}

case "$1" in 
	sysinit )
		rc_sysinit
		;;
	nonetwork )
		rc_nonetwork
		;;
	network )
		rc_network
		;;
	start_network )
		rc_start_network
		;;
	reboot )
		rc_shutdown
		/sbin/reboot -f
		;;
	shutdown )
		rc_shutdown
		/sbin/halt -p
		;;
esac


